#!/usr/bin/env bash
# =============================================================================
# Radeef HRMS - provision a tenant on the host (run as root).
#
# Usage:
#   sudo ops/new-tenant.sh [--mode pm2|docker] [--email <certbot-email>] [--skip-certbot] <tenant> <domain> <port>
#   sudo ops/new-tenant.sh --nginx-only [--email <e>] [--skip-certbot] <tenant> <domain> <port>
#        (existing tenant: only render/refresh the Nginx site + certificate)
#
# Creates:
#   - system user `radeef` (uid 1001 when free = the Docker image user)
#   - dedicated Postgres role <tenant>_app + database <tenant>_erp (random password, owner-only),
#     role defaults statement_timeout=30s and idle_in_transaction_session_timeout=60s
#   - /etc/radeef/<tenant>.env (chmod 600) with DATABASE_URL (connection_limit=5), SESSION_SECRET
#     and DATA_ENCRYPTION_KEY generated by `openssl rand`, and SMTP_* (from TENANT_SMTP_* or empty;
#     missing ones are listed before anything is created)
#   - /var/lib/radeef/<tenant>/uploads, /var/backups/radeef/<tenant>, /opt/radeef/<tenant>
#   - Nginx site from ops/nginx/tenant.conf.template + Let's Encrypt certificate (certbot --webroot)
# It never overwrites an existing env file, role or database.
# =============================================================================
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

MODE="${RADEEF_MODE:-pm2}"
EMAIL=""
SKIP_CERTBOT=0
NGINX_ONLY=0
ARGS=()
SERVICE_USER="${SERVICE_USER:-radeef}"
SERVICE_UID=1001
PG_HOST_PM2="${PG_HOST_PM2:-127.0.0.1}"
PG_HOST_DOCKER="${PG_HOST_DOCKER:-host.docker.internal}"
PG_PORT="${PG_PORT:-5432}"
TEMPLATE="$SCRIPT_DIR/nginx/tenant.conf.template"
MAINTENANCE_HTML="$SCRIPT_DIR/nginx/maintenance.html"
UPSTREAM_DIR="${UPSTREAM_DIR:-/etc/nginx/radeef-upstreams}"
DOMAIN_RE='^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$'

while (($#)); do
  case "$1" in
    --mode) MODE="${2:?--mode needs a value}"; shift 2 ;;
    --email) EMAIL="${2:?--email needs a value}"; shift 2 ;;
    --skip-certbot) SKIP_CERTBOT=1; shift ;;
    --nginx-only) NGINX_ONLY=1; shift ;;
    -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown option: $1" ;;
    *) ARGS+=("$1"); shift ;;
  esac
done
((${#ARGS[@]} == 3)) || die "usage: sudo ops/new-tenant.sh [options] <tenant> <domain> <port> (see --help)"
TENANT="${ARGS[0]}"
DOMAIN="${ARGS[1],,}"
PORT="${ARGS[2]}"

[[ "$(id -u)" -eq 0 ]] || die "run as root (sudo)"
[[ "$MODE" == "pm2" || "$MODE" == "docker" ]] || die "--mode must be pm2 or docker"
validate_tenant "$TENANT"
[[ "$DOMAIN" =~ $DOMAIN_RE ]] || die "invalid domain: $DOMAIN"
[[ "$PORT" =~ ^[0-9]{4,5}$ ]] && ((PORT >= 1024 && PORT <= 64000)) || die "port must be 1024..64000"
[[ -z "$EMAIL" || "$EMAIL" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[a-z]{2,}$ ]] || die "invalid --email"
[[ -f "$TEMPLATE" ]] || die "missing $TEMPLATE"

require_cmd nginx openssl sed
((SKIP_CERTBOT)) || require_cmd certbot

ENV_FILE="$(tenant_env_file "$TENANT")"

# ------------------------------------------------------------------ SMTP pre-provisioning check (DEC-009)
# Optional TENANT_SMTP_{HOST,PORT,SECURE,USER,PASS,FROM} in the environment are written into the
# new env file (sudo -E or `sudo TENANT_SMTP_HOST=... ops/new-tenant.sh ...`). They stay empty
# until the owner approves a mail provider; missing values are listed but do not block.
TENANT_SMTP_HOST="${TENANT_SMTP_HOST:-}"
TENANT_SMTP_PORT="${TENANT_SMTP_PORT:-}"
TENANT_SMTP_SECURE="${TENANT_SMTP_SECURE:-}"
TENANT_SMTP_USER="${TENANT_SMTP_USER:-}"
TENANT_SMTP_PASS="${TENANT_SMTP_PASS:-}"
TENANT_SMTP_FROM="${TENANT_SMTP_FROM:-}"
SMTP_MISSING=()
SMTP_BAD_RE='["$`\\]'
for v in TENANT_SMTP_HOST TENANT_SMTP_PORT TENANT_SMTP_SECURE TENANT_SMTP_USER TENANT_SMTP_PASS TENANT_SMTP_FROM; do
  if [[ "${!v}" =~ $SMTP_BAD_RE || "${!v}" == *$'\n'* ]]; then
    die "$v must not contain double quotes, \$, backticks, backslashes or newlines"
  fi
done
for v in TENANT_SMTP_HOST TENANT_SMTP_USER TENANT_SMTP_PASS TENANT_SMTP_FROM; do
  [[ -n "${!v}" ]] || SMTP_MISSING+=("$v")
done
if ((NGINX_ONLY == 0 && ${#SMTP_MISSING[@]} > 0)); then
  warn "pre-provisioning check: SMTP for this tenant is incomplete (missing: ${SMTP_MISSING[*]}). SMTP_* will be written EMPTY; the tenant sends no e-mail until they are filled in."
fi

DB_IDENT="${TENANT//-/_}"
DB_NAME="${DB_IDENT}_erp"
DB_ROLE="${DB_IDENT}_app"

# ------------------------------------------------------------------ service user + dirs
ensure_service_user() {
  if id "$SERVICE_USER" >/dev/null 2>&1; then return 0; fi
  if getent passwd "$SERVICE_UID" >/dev/null; then
    warn "uid $SERVICE_UID is taken: creating $SERVICE_USER with another uid (Docker volumes need uid 1001, see docs/RUNBOOK.md)"
    useradd --system --create-home --home-dir "/home/$SERVICE_USER" --shell /bin/bash "$SERVICE_USER"
  else
    groupadd --system --gid "$SERVICE_UID" "$SERVICE_USER" 2>/dev/null || true
    useradd --system --uid "$SERVICE_UID" --gid "$SERVICE_UID" --create-home --home-dir "/home/$SERVICE_USER" --shell /bin/bash "$SERVICE_USER"
  fi
  passwd -l "$SERVICE_USER" >/dev/null
  log "created system user $SERVICE_USER"
}

ensure_dirs() {
  local owner="$SERVICE_USER:$SERVICE_USER"
  install -d -m 755 "$ENV_DIR" "$RADEEF_ROOT" "$DATA_DIR" "$BACKUP_DIR"
  install -d -m 750 -o "$SERVICE_USER" -g "$SERVICE_USER" \
    "$RADEEF_ROOT/$TENANT" "$RADEEF_ROOT/releases" "$DATA_DIR/$TENANT" "/var/log/radeef"
  install -d -m 700 -o "$SERVICE_USER" -g "$SERVICE_USER" "$BACKUP_DIR/$TENANT"
  install -d -m 750 "$DATA_DIR/$TENANT/uploads"
  if [[ "$MODE" == "docker" ]]; then owner="1001:1001"; fi
  chown "$owner" "$DATA_DIR/$TENANT/uploads"
}

# ------------------------------------------------------------------ database
create_database() {
  require_cmd psql sudo
  local exists
  exists="$(sudo -u postgres psql -tAq -v ON_ERROR_STOP=1 -v role="$DB_ROLE" -v db="$DB_NAME" <<'SQL'
SELECT (SELECT count(*) FROM pg_roles WHERE rolname = :'role') + (SELECT count(*) FROM pg_database WHERE datname = :'db');
SQL
)"
  [[ "$exists" == "0" ]] || die "Postgres role $DB_ROLE or database $DB_NAME already exists; refusing to touch it"

  DB_PASSWORD="$(openssl rand -hex 32)"
  log "creating Postgres role $DB_ROLE and database $DB_NAME"
  # The password travels through stdin (not argv), so it never shows up in `ps`.
  sudo -u postgres psql -q -v ON_ERROR_STOP=1 -v role="$DB_ROLE" -v db="$DB_NAME" <<SQL
\\set pw '$DB_PASSWORD'
CREATE ROLE :"role" LOGIN PASSWORD :'pw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION CONNECTION LIMIT 40;
-- DEC-004: session defaults for every connection of this role (app, jobs, seed). Migrations
-- override them through the URL "options" parameter (ops/deploy.sh); pg_dump sets its own.
ALTER ROLE :"role" SET statement_timeout = '30s';
ALTER ROLE :"role" SET idle_in_transaction_session_timeout = '60s';
CREATE DATABASE :"db" OWNER :"role" ENCODING 'UTF8' TEMPLATE template0;
REVOKE ALL ON DATABASE :"db" FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE :"db" TO :"role";
\\connect :"db"
ALTER SCHEMA public OWNER TO :"role";
REVOKE ALL ON SCHEMA public FROM PUBLIC;
SQL
}

write_env_file() {
  local host url session_secret data_key
  [[ "$MODE" == "docker" ]] && host="$PG_HOST_DOCKER" || host="$PG_HOST_PM2"
  url="postgresql://${DB_ROLE}:${DB_PASSWORD}@${host}:${PG_PORT}/${DB_NAME}?schema=public&connection_limit=${APP_CONNECTION_LIMIT}&pool_timeout=20"
  session_secret="$(openssl rand -base64 48 | tr -d '\n')"
  data_key="$(openssl rand -base64 32 | tr -d '\n')"
  (
    umask 077
    cat >"$ENV_FILE.tmp" <<EOF
# Radeef tenant "$TENANT" ($DOMAIN) - generated by ops/new-tenant.sh on $(date -u '+%Y-%m-%d %H:%M UTC').
# chmod 600. NEVER commit or copy this file. Back up DATA_ENCRYPTION_KEY separately (password manager):
# losing it makes encrypted fields unreadable. Reference: .env.example
NODE_ENV="production"
PORT="$PORT"
DATABASE_URL="$url"
SESSION_SECRET="$session_secret"
DATA_ENCRYPTION_KEY="$data_key"
UPLOAD_DIR="$DATA_DIR/$TENANT/uploads"
PRISMA_LOG_QUERIES="false"

# Outgoing e-mail. Empty until the owner approves a provider (docs/processors.md).
SMTP_HOST="$TENANT_SMTP_HOST"
SMTP_PORT="${TENANT_SMTP_PORT:-587}"
SMTP_SECURE="$TENANT_SMTP_SECURE"
SMTP_USER="$TENANT_SMTP_USER"
SMTP_PASS="$TENANT_SMTP_PASS"
SMTP_FROM="$TENANT_SMTP_FROM"

# First admin: prefer `npm run admin:create -- <email>` (prints a one-time password).
# If you use the seed instead, fill these, run it once, then REMOVE ADMIN_PASSWORD.
ADMIN_EMAIL=""
ADMIN_PASSWORD=""
EOF
  )
  chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE.tmp"
  chmod 600 "$ENV_FILE.tmp"
  mv -f "$ENV_FILE.tmp" "$ENV_FILE"
  log "wrote $ENV_FILE (600, $SERVICE_USER)"
}

# ------------------------------------------------------------------ nginx + TLS
disable_conflicting_sites() {
  local f target="/etc/nginx/sites-enabled/$DOMAIN.conf"
  for f in /etc/nginx/sites-enabled/*; do
    [[ -e "$f" || -L "$f" ]] || continue
    [[ "$f" == "$target" ]] && continue
    if grep -Eq "server_name[^;]*[[:space:]]${DOMAIN//./\\.}[[:space:];]" "$f" 2>/dev/null; then
      warn "disabling old Nginx site $f (it also serves $DOMAIN)"
      if [[ -L "$f" ]]; then rm -f "$f"; else mv "$f" "/etc/nginx/sites-available/$(basename "$f").disabled-$(timestamp)"; fi
    fi
  done
}

render_site() {
  sed -e "s/__DOMAIN__/$DOMAIN/g" -e "s/__PORT__/$PORT/g" -e "s/__TENANT__/$TENANT/g" "$TEMPLATE"
}

setup_nginx() {
  install -d -m 755 /var/www/certbot /var/www/radeef-maintenance "$UPSTREAM_DIR"
  install -m 644 "$MAINTENANCE_HTML" /var/www/radeef-maintenance/__maintenance.html
  printf 'server 127.0.0.1:%s max_fails=0;\n' "$PORT" >"$UPSTREAM_DIR/$TENANT.conf"
  chmod 644 "$UPSTREAM_DIR/$TENANT.conf"

  local avail="/etc/nginx/sites-available/$DOMAIN.conf" enabled="/etc/nginx/sites-enabled/$DOMAIN.conf"
  local cert="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
  disable_conflicting_sites

  if [[ ! -f "$cert" ]]; then
    if ((SKIP_CERTBOT)); then
      warn "no certificate for $DOMAIN and --skip-certbot given: installing an HTTP-only bootstrap site"
    fi
    # Bootstrap: HTTP only, serves ACME challenges and the maintenance page.
    cat >"$avail" <<EOF
# Temporary bootstrap site for $DOMAIN (ops/new-tenant.sh). Replaced once a certificate exists.
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    server_tokens off;
    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; default_type "text/plain"; }
    location / { root /var/www/radeef-maintenance; try_files /__maintenance.html =503; }
}
EOF
    ln -sfn "$avail" "$enabled"
    nginx -t -q || { rm -f "$enabled"; die "nginx -t failed for the bootstrap site"; }
    systemctl reload nginx
    if ((SKIP_CERTBOT)); then return 0; fi
    log "requesting a Let's Encrypt certificate for $DOMAIN (DNS must already point here)"
    local email_args=(--register-unsafely-without-email)
    [[ -n "$EMAIL" ]] && email_args=(--email "$EMAIL")
    certbot certonly --webroot -w /var/www/certbot -d "$DOMAIN" --non-interactive --agree-tos "${email_args[@]}"
  fi

  render_site >"$avail.new"
  mv -f "$avail.new" "$avail"
  ln -sfn "$avail" "$enabled"
  if ! nginx -t -q; then
    rm -f "$enabled"
    die "nginx -t failed for $avail (site disabled; fix and re-run with --nginx-only)"
  fi
  systemctl reload nginx
  log "Nginx: https://$DOMAIN -> 127.0.0.1:$PORT"

  local hook=/etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh
  if [[ -d /etc/letsencrypt && ! -f "$hook" ]]; then
    install -d -m 755 "$(dirname "$hook")"
    printf '#!/bin/sh\nnginx -t -q && systemctl reload nginx\n' >"$hook"
    chmod 755 "$hook"
  fi
}

# ------------------------------------------------------------------ main
ensure_service_user

if ((NGINX_ONLY == 0)); then
  [[ ! -e "$ENV_FILE" ]] || die "$ENV_FILE already exists; refusing to overwrite (use --nginx-only for an existing tenant)"
  for f in "$ENV_DIR"/*.env; do
    [[ -f "$f" ]] || continue
    if [[ "$(env_get "$f" PORT)" == "$PORT" ]]; then die "port $PORT is already used by $f"; fi
  done
  if command -v ss >/dev/null && ss -ltnH "sport = :$PORT" | grep -q .; then
    die "port $PORT is already listening on this host"
  fi
  ensure_dirs
  create_database
  write_env_file
fi

setup_nginx

cat <<EOF

Tenant "$TENANT" is provisioned. Next steps:
  1. Schema + seed:
       PM2:    sudo -iu $SERVICE_USER $RADEEF_ROOT/src/ops/deploy.sh $TENANT
       Docker: add a "$TENANT" service (port 127.0.0.1:$PORT:3000, env_file $ENV_FILE,
               volume $DATA_DIR/$TENANT/uploads:/app/uploads) to docker-compose.yml, then
               sudo ops/deploy.sh --mode docker $TENANT
  2. First administrator (prints a one-time password):
       cd $RADEEF_ROOT/src && sudo -u $SERVICE_USER node --env-file=$ENV_FILE scripts/create-admin.mjs admin@$DOMAIN
     (Docker: docker run --rm --env-file $ENV_FILE --add-host host.docker.internal:host-gateway radeef:live-$TENANT node scripts/create-admin.mjs admin@$DOMAIN)
  3. Backups: ops/backup.sh --all already picks up $ENV_FILE (check the cron entry).
  4. Store DATA_ENCRYPTION_KEY from $ENV_FILE in the company password manager.
EOF
